### PR TITLE
feat: Adding Keptn pattern

### PR DESCRIPTION
**Pull request by heckelmann**
Signed-off-by: Christian Heckelmann <christian.heckelmann@dynatrace.com>

*Description of changes:*

Adding Keptn Control Plane Pattern requested within this PR: https://github.com/aws-samples/ssp-eks-patterns/compare/main...heckelmann:keptn-pattern?expand=1

This Pattern does not include the Keptn Execution Plane AddOn (https://github.com/keptn-sandbox/keptn-ssp-addons), as this will only work with an existing Keptn Control Plane.

A Secrets Manager Secret is expected as described within the README.md file.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by parkand1 — COMMENTED** [review]
Did you mean to say replicated to us-east-2 and us-west-2?

**Review by parkand1 — CHANGES_REQUESTED** [review]
The code makes sense but there currently is no method for deploying the stack. Can you add an import path to /bin/main.ts?

**Comment by heckelmann** [comment]
> Did you mean to say replicated to us-east-2 and us-west-2?

Think you mean the README.md line. 
To be honest, I just adopted the line from argo, as I was not sure if this is needed here.

**Comment by heckelmann** [comment]
> The code makes sense but there currently is no method for deploying the stack. Can you add an import path to /bin/main.ts?

I've adopted your change requests. Please let me know if there is anything else I should do/change if needed.

**Comment by shapirov103** [comment]
@parkand1 anything pending from your side?

**Comment by parkand1** [comment]
Apologies for the delay here - this is good to go for me!

**Review by parkand1 — APPROVED** [review]
LGTM

**Pull request merged**
